micron_sonar_node:
  ros__parameters:
    
    debug: false
    
    baudrate: 115200
    port: "/tmp/micron"
    
    udpPort: 4000
    udpServer: ""
    
    max_distance: 5.0     
    min_distance: 0.8
    resolution: 0.01        
    
    stare_left_limit: false
    left_limit: 180.0
    right_limit: -179.0
    
    angular_resolution: 1.0 
    
    gain: 0.01              
    speed_of_propagation: 1470.0    
    
    low_resolution: true  
    
    continous: false
    invert: false          
    
    frequency_out: 15.0     
    intensity_threshold: 50.0 
    min_dist_considered: 0.1
    peak_proportion: 1.25
    timeout_receive_data: 5000
    
    should_turn_on_motor: true